### ISSUE TITLE
update the nppPluginList "homepage" entry

### ISSUE THREAD

**Issue by pryrt** [PlanetCNC/PlanetCNCNpp#1]
The nppPluginList entries for your plugin ([64bit](https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x64.json) and [32bit](https://github.com/notepad-plus-plus/nppPluginList/blob/master/src/pl.x86.json)) point users to your [main homepage](https://planet-cnc.com/): 
![image](https://user-images.githubusercontent.com/17455758/129361997-6d362c02-94dc-4ea6-9554-b47122a91b06.png)

The problem is, if someone is trying to find out what your plugin is or how it works before downloading it, all they have to go by is what they see in Plugins Admin:
![image](https://user-images.githubusercontent.com/17455758/129362078-a94a2937-635f-4ab9-a9ee-9da03e11936e.png)
... and when they go to that website, it tells them about CNC USB controllers, which isn't helpful at all to a Notepad++ user looking for information about your plugin and what kind of expressions it can calculate.

Instead, if you changed the nppPluginList "homepage" entry to `https://github.com/PlanetCNC/PlanetCNCNpp/`, it would take them here, which actually tells them about the plugin, and lets them know that it really is a plugin that does mathematical expression calculations in Notepad++, with details of what kinds of expressions it can calculate.

**Comment by PlanetCNC** [comment]
Fixed in version 1.1
